//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4016
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Reflection;
using System.Resources;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

[assembly: AssemblyCompany("Vestris Inc.")]
[assembly: AssemblyProduct("ResourceLib")]
[assembly: AssemblyCopyright("Copyright (c) Vestris Inc.")]
[assembly: AssemblyTrademark("All Rights Reserved")]
[assembly: CLSCompliant(false)]
[assembly: AssemblyDelaySign(false)]
[assembly: AssemblyVersion("1.2.28064.0")]
[assembly: AssemblyFileVersion("1.2.28064.0")]


